[package]
name = "manager_views"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "2"
actix-rt = "1.0"

chrono = { version = "= 0.4.29" }
serde_json ={ version = "1.0", default-features = false, features = ["alloc"]}
futures = "0.3.5"
serde = "1"